// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import DisableFormController from "./disable_form_controller.js"
application.register("disable-form", DisableFormController)

import GameBoardController from "./game_board_controller.js"
application.register("game-board", GameBoardController)

import RandomNameController from "./random_name_controller.js"
application.register("random-name", RandomNameController)

import RepeatableFieldController from "./repeatable_field_controller.js"
application.register("repeatable-field", RepeatableFieldController)

import SortableCards from './sortable_cards_controller.js'
application.register('sortable-cards', SortableCards)

import TooltipController from "./tooltip_controller.js"
application.register("tooltip", TooltipController)
