#!/bin/bash

source $OPENSHIFT_CARTRIDGE_SDK_BASH
source "${OPENSHIFT_RUBY_DIR}/lib/ruby_context"

pushd ${OPENSHIFT_REPO_DIR} > /dev/null
mv config/database.openshift.yml config/database.yml
echo "exec rake db:migrate RAILS_ENV=${RAILS_ENV:-production}"
ruby_context "bundle exec rake db:migrate RAILS_ENV=${RAILS_ENV:-production}"
popd > /dev/null