#!/bin/bash

source "${OPENSHIFT_RUBY_DIR}/lib/ruby_context"
pushd ${OPENSHIFT_REPO_DIR} 1> /dev/null
SAVED_GIT_DIR=$GIT_DIR
unset GIT_DIR
sed -i /mingw32/d Gemfile.lock
ruby_context "bundle install"
export GIT_DIR=$SAVED_GIT_DIR
popd 1> /dev/null