class RandomNamer
  ADJECTIVES = %w[
abaft abandoned abashed aberrant abhorrent abiding abject ablaze able abnormal aboard aboriginal abortive abounding abrasive abrupt absent absorbed absorbing abstracted absurd abundant abusive acceptable accessible accidental accurate acid acidic acoustic acrid actually ad hoc adamant adaptable addicted adhesive adjoining adorable adventurous afraid aggressive agonizing agreeable ahead ajar alcoholic alert alike alive alleged alluring aloof amazing ambiguous ambitious amuck amused amusing ancient angry animated annoyed annoying anxious apathetic aquatic aromatic arrogant ashamed aspiring assorted astonishing attractive auspicious automatic available average awake aware awesome awful axiomatic
barbarous bashful bawdy beautiful befitting belligerent beneficial bent berserk best better bewildered big billowy bite-sized bitter bizarre black black-and-white bloody blue blue-eyed blushing boiling boorish bored boring bouncy boundless brainy brash brave brawny breakable breezy brief bright bright broad broken brown bumpy burly bustling busy
calculating callous calm capable capricious careful careless caring cautious ceaseless certain changeable charming cheap cheerful chemical chief childlike chilly chivalrous chubby chunky clammy classy clean clear clever cloistered cloudy closed clumsy cluttered coherent cold colorful colossal combative comfortable common complete complex concerned condemned confused conscious cooing cool cooperative coordinated courageous cowardly crabby craven crazy creepy crooked crowded cruel cuddly cultured cumbersome curious curly curved curvy cut cute cute cynical
daily damaged damaging damp dangerous dapper dark dashing dazzling dead deadpan deafening dear debonair decisive decorous deep deeply defeated defective defiant delicate delicious delightful demonic delirious dependent depressed deranged descriptive deserted detailed determined devilish didactic different difficult diligent direful dirty disagreeable disastrous discreet disgusted disgusting disillusioned dispensable distinct disturbed divergent dizzy domineering doubtful drab draconian dramatic dreary drunk dry dull dusty dusty dynamic dysfunctional
early earsplitting earthy easy eatable economic educated efficacious efficient eight elastic elated elderly electric elegant elfin elite embarrassed eminent empty enchanted enchanting encouraging endurable energetic enormous entertaining enthusiastic envious equable equal erect erratic ethereal evanescent evasive even excellent excited exciting exclusive exotic expensive extra-large extra-small exuberant exultant
faded faint fair faithful fallacious false familiar famous fanatical fancy fantastic far far-flung fascinated fast fat faulty fearful fearless feeble feigned female fertile festive few fierce filthy fine finicky first five fixed flagrant flaky flashy flat flawless flimsy flippant flowery fluffy fluttering foamy foolish foregoing forgetful fortunate four frail fragile frantic free freezing frequent fresh fretful friendly frightened frightening full fumbling functional funny furry furtive future futuristic fuzzy
gainful gamy gaping garrulous gaudy general gentle giant giddy gifted gigantic glamorous gleaming glib glistening glorious glossy godly good goofy gorgeous graceful grandiose grateful gratis gray greasy great greedy green grey grieving groovy grotesque grouchy grubby gruesome grumpy guarded guiltless gullible gusty guttural
half hallowed halting handsome handsomely handy hanging hapless happy hard hard-to-find harmonious harsh hateful heady healthy heartbreaking heavenly heavy hellish helpful helpless hesitant hideous high highfalutin high-pitched hilarious hissing historical holistic hollow homeless homely honorable horrible hospitable hot huge hulking humdrum humorous hungry hurried hurt hushed husky hypnotic hysterical
icy idiotic ignorant ill illegal ill-fated ill-informed illustrious imaginary immense imminent impartial imperfect impolite important imported impossible incandescent incompetent inconclusive industrious incredible inexpensive infamous innate innocent inquisitive insidious instinctive intelligent interesting internal invincible irate irritating itchy
jagged jazzy jealous jittery jobless jolly joyous judicious juicy jumbled jumpy juvenile
keen kind kindhearted kindly knotty knowing knowledgeable known
lackadaisical lacking lame lamentable languid large last late laughable lavish lazy lean learned left legal lethal level lewd light like likeable limping literate little lively lively living lonely long longing long-term loose lopsided loud loutish lovely loving low lowly lucky ludicrous lumpy lush luxuriant lying lyrical
macho maddening madly magenta magical magnificent majestic makeshift male malicious mammoth maniacal many marked massive married marvelous material materialistic mature mean measly meaty medical meek mellow melodic melted merciful mere messy mighty military milky mindless miniature minor miscreant misty mixed moaning modern moldy momentous motionless mountainous muddled mundane murky mushy mute mysterious
nappy narrow nasty natural naughty nauseating near neat nebulous necessary needless needy neighborly nervous new next nice nifty nimble nine nippy noiseless noisy nonchalant nondescript nonstop normal nostalgic nosy noxious null numberless numerous nutritious nutty
obedient obeisant obese obnoxious obscene obsequious observant obsolete obtainable oceanic odd offbeat old old-fashioned omniscient one onerous open opposite optimal orange ordinary organic ossified outgoing outrageous outstanding oval overconfident overjoyed overrated overt overwrought
painstaking pale paltry panicky panoramic parallel parched parsimonious past pastoral pathetic peaceful penitent perfect periodic permissible perpetual petite petite phobic physical picayune pink piquant placid plain plant plastic plausible pleasant plucky pointless poised polite political poor possessive possible powerful precious premium present pretty previous pricey prickly private probable productive profuse protective proud psychedelic psychotic public puffy pumped puny purple purring pushy puzzled puzzling
quaint quarrelsome questionable quick quickest quiet quirky quixotic quizzical
racial ragged rainy rambunctious rampant rapid rare raspy ratty ready real rebel receptive recondite red redundant reflective regular relieved remarkable reminiscent repulsive resolute resonant responsible rhetorical rich right righteous rightful rigid ripe ritzy roasted robust romantic roomy rotten rough round royal ruddy rude rural rustic ruthless
sad safe salty same sassy satisfying savory scandalous scarce scared scary scattered scientific scintillating scrawny screeching second second-hand secret secretive sedate seemly selective selfish separate serious shaggy shaky shallow sharp shiny shivering shocking short shrill shut shy sick silent silent silky silly simple simplistic sincere six skillful skinny sleepy slim slimy slippery sloppy slow small smart smelly smiling smoggy smooth sneaky snobbish snotty soft soggy solid somber sophisticated sordid sore sore sour sparkling special spectacular spicy spiffy spiky spiritual spiteful splendid spooky spotless spotted spotty spurious squalid square squealing squeamish staking stale standing statuesque steadfast steady steep stereotyped sticky stiff stimulating stingy stormy straight strange striped strong stupendous stupid sturdy subdued subsequent substantial successful succinct sudden sulky super superb superficial supreme swanky sweet sweltering swift symptomatic synonymous
tacit tacky talented tall tame tan tangible tangy tart tasteful tasteless tasty tawdry tearful tedious teeny teeny-tiny telling temporary ten tender tense tense tenuous terrible terrific tested testy thankful therapeutic thick thin thinkable third thirsty thirsty thoughtful thoughtless threatening three thundering tidy tight tightfisted tiny tired tiresome toothsome torpid tough towering tranquil trashy tremendous tricky trite troubled truculent true truthful two typical
ugliest ugly ultra unable unaccountable unadvised unarmed unbecoming unbiased uncovered understood undesirable unequal unequaled uneven unhealthy uninterested unique unkempt unknown unnatural unruly unsightly unsuitable untidy unused unusual unwieldy unwritten upbeat uppity upset uptight used useful useless utopian utter uttermost
vagabond vague valuable various vast vengeful venomous verdant versed victorious vigorous violent violet vivacious voiceless volatile voracious vulgar
waggish waiting wakeful wandering wanting warlike warm wary wasteful watery weak wealthy weary well-groomed well-made well-off well-to-do wet whimsical whispering white whole wholesale wicked wide wide-eyed wiggly wild willing windy wiry wise wistful witty woebegone womanly wonderful wooden woozy workable worried worthless wrathful wretched wrong wry
  ].freeze

  NOUNS = %w[
Cellar Chapel Moat Harbinger Merchant Vassal Village Workshop Bureaucrat Gardens Militia Moneylender Poacher Smithy Throne Room Bandit Council Festival Laboratory Library Market Mine
Sentry Witch Artisan Chancellor Woodcutter Feast Spy Thief Adventurer Courtyard Lurker Pawn Masquerade Town Steward Swindler Well Baron Bridge Conspirator Diplomat Ironworks Mill
Secret Passage Courtier Duke Minion Patrol Torturer Post Upgrade Harem Nobles Chamber Hall Coppersmith Scout Saboteur Tribute Embargo Haven Lighthouse Native
Pearl Diver Ambassador Fish Lookout Smugglers Warehouse Caravan Cutpurse Island Navigator Pirate Ship Salvager Sea Hag Treasure Map Bazaar Explorer Ghost Outpost Tactician Treasury Wharf
Vineyard Herbalist Apothecary Pool University Alchemist Familiar Philosopher Stone Potion Golem Apprentice Possession Loan Trade Route Watchtower Bishop Monument Quarry Talisman Worker City Contraband House Mint Mountebank Rabble Royal Seal Vault Venture Goons Hoard Star Bank Forge King Court Peddler Platinum Colony Hamlet Fortune Teller
Menagerie Horse Tournament Prizes Bag Gold Diadem Followers Princess Steed Harvest Horn Hunt Party Jester Fairgrounds Crossroads Duchess Fool Oasis Oracle Scheme Tunnel Jack Noble Brigand Nomad Camp Silk Road Spice Trader Cache Cartographer Embassy Haggler Highway Inn Mandarin Margrave Stables
Border Farmland Ruin Survivors Spoils Shelter Hovel Necropolis Estate Beggar Squire Vagrant Forager Hermit Madman Square Sage Storeroom Urchin Mercenary
Armory Death Cart Feodum Fortress Ironmonger Marauder Procession Rats Scavenger Minstrel Band Misfits Catacombs Count Counterfeit Cultist Graverobber Junk Dealer Knights Dames Sirs Bailey Mystic Rogue Altar Grounds Candlestick Maker Stonemason Doctor Masterpiece Advisor Plaza
Taxman Herald Baker Butcher Journeyman Guild Soothsayer Coin Realm Page Hunter Warrior Hero Champion Peasant Soldier Fugitive Disciple Teacher Ratcatcher Amulet Guard Dungeon
Gear Guide Duplicate Magpie Messenger Miser Port Ranger Artificer Troll Lands Giant Woods Relic Carriage Storyteller Swamp Trove Wine Hireling Alms
Quest Fair Bonfire Expedition Ferry Plan Mission Pilgrimage Ball Raid Seaway Arts Inheritance Engineer Quarter Overlord Blacksmith Encampment
Plunder Patrician Emporium Settlers Castle Catapult Rocks Chariot Race Enchantress Farmer Gladiator Fortune Sacrifice Temple Villa
Archive Capital Charm Crown Forum Groundskeeper Legionary Hunt Triumph Annex Advance Tax Banquet Ritual Salt Earth Wedding Windfall Conquest Aqueduct Arena Fort Basilica
Baths Battlefield Colonnade Shrine Fountain Keep Labyrinth Mountain Pass Museum Obelisk Orchard Palace Tomb Tower Arch Wall Wolf Den Will-o'-Wisp Wish Druid Hound Guardian Monastery Pixie Goat Tracker Pouch Imp Changeling Fool Coin Leprechaun Night Watchman Cave Magic Lamp Bard Cemetery Mirror Conclave Devil
Exorcist Necromancer Zombie Mason Shepherd Pasture Skulk Cobbler Crypt Sin Idol Pooka Grove Tormentor Vampire Bat Werewolf Raider Gift
Field Flame Forest Moon River Sea Sky Sun Wind Omens Delusion Envy Famine Fear Greed Haunting Locusts Misery
Plague Poverty War Horn Lantern Ducat Lackeys Troupe Cargo Experiment Flag Bearer Hideout Inventor Patron Priest Research Recruiter Scepter Scholar Sculptor
Seer Swashbuckler Chest Treasurer Key Villain Cathedral Gate Pageant Sewers Star Chart Exploration Silos Plot Academy Capitalism Fleet Guildhall Piazza Network Barracks Crop
Innovation Canal Citadel Envoy Sauna Avanto Governor Stash Prince
  ]

  def self.random_name
    [ADJECTIVES.sample, NOUNS.sample].join(' ').titleize
  end
end
